# Uncomment the next line to define a global platform for your project
 platform :ios, '16.4'

target 'ToDoey' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ToDoey
  pod 'RealmSwift'
  pod 'SwipeCellKit'

end
